"""Seed phrases for varying the opening of steganographic cover text.

A fixed list of short phrases is used so that different input messages produce
cover text with different openings.  The phrase is selected deterministically
via a SHA-256 hash of the plaintext data and is prepended to the cover text so
the decoder can recover it without knowing the original message.
"""

from __future__ import annotations

import hashlib

# 256 short seed phrases — each is a plausible English sentence opener.
# IMPORTANT: no phrase may be a prefix of another (ensures unambiguous matching).
SEED_PHRASES: tuple[str, ...] = (
    # --- General / expository ---
    "According to experts,",
    "After years of research,",
    "Although it may seem surprising,",
    "I actually think",
    "You remember when",
    "As we look ahead,",
    "Every time I see",
    "I was just thinking",
    "So here's the thing,",
    "My friend once told",
    "By all accounts,",
    "Contrary to popular belief,",
    "I keep hearing about",
    "Despite initial setbacks,",
    "During the past decade,",
    "Even in ancient times,",
    "Honestly, I never",
    "It's funny how",
    "Few people realize that",
    "You know what's weird,",
    "I spent a lot of",
    "The other day I",
    "Given the circumstances,",
    "I used to believe",
    "Someone recently asked",
    "However, recent findings",
    "I'm not sure why",
    "Back when I was",
    "We all know that",
    "In hindsight, it seems",
    "In many ways, the story",
    "In recent decades,",
    "Whenever I think about",
    "In the early morning hours,",
    "I've always wondered",
    "In the years that followed,",
    "Most people don't",
    "Interestingly enough,",
    "If you've ever tried",
    "I finally figured out",
    "It is often said that",
    "It is worth noting that",
    "It may come as a surprise,",
    "My favorite part about",
    "I read somewhere that",
    "Just as importantly,",
    "Growing up, I always",
    "So apparently,",
    "I never really understood",
    "Many people are unaware that",
    "You'd be surprised how",
    "More importantly,",
    "A while back, I",
    "Not everyone is aware that",
    "Not long ago, a team",
    "Nowadays, it is common",
    "I was talking to",
    "On closer inspection,",
    "On the other hand,",
    "Last year, I decided",
    "One could argue that",
    "One of the most fascinating",
    "One of the most overlooked",
    "I know it sounds",
    "Here's something I",
    "When I first heard",
    "Rather than focusing on",
    "Recent studies have shown",
    "I don't usually talk",
    "It took me years",
    "I just found out",
    "Nobody ever tells you",
    "I've been meaning to",
    "What really gets me",
    "I can't help but",
    "Surprisingly, the answer",
    "The answer, it turns out,",
    "If I'm being honest,",
    "So I was reading",
    "The weird thing is",
    "The discovery was made",
    "I remember the first",
    "The evidence is clear:",
    "The fact remains that",
    "The first thing to understand",
    "People always ask me",
    "I had no idea",
    "The idea behind this",
    "You wouldn't believe how",
    "The importance of this",
    "The interesting thing about",
    "The key to understanding",
    "At some point, I",
    "I think the reason",
    "It's hard to explain,",
    "My whole life, I",
    "I only recently learned",
    "The thing about this",
    "The problem, of course,",
    "The question of how",
    "The reason for this",
    "The relationship between",
    "The results were unexpected:",
    "I've noticed that",
    "The story begins in",
    "When you really think",
    "The truth of the matter",
    "I didn't expect to",
    "It still surprises me",
    "I keep coming back",
    "There is no denying that",
    "The way I see",
    "I'm starting to think",
    "Have you ever noticed",
    "To put it in context,",
    "To this day, many",
    "Today, we take for granted",
    "For what it's worth,",
    "Under normal circumstances,",
    "Unlike what many assume,",
    "Until recently, scientists",
    "What began as a small",
    "What is less well known",
    "What makes this particularly",
    "When the first reports",
    "While it is true that",
    "While much attention has",
    "With each passing year,",
    "I wish someone had",
    "Lately, I've been",
    "I got curious about",
    # --- Nature / science ---
    "Across the vast plains,",
    "Along the rocky coastline,",
    "At the edge of the forest,",
    "Beneath the surface of",
    "If you ask me,",
    "I want to talk",
    "One thing I know is",
    "Deep beneath the ocean,",
    "I tried explaining this",
    "You might not know",
    "I heard that in",
    "It always seemed like",
    "High in the mountain passes,",
    "In the depths of winter,",
    "In the world of marine",
    "Life in the desert requires",
    "I could be wrong,",
    "Mountains have always inspired",
    "Near the banks of the river,",
    "When we were kids,",
    "On the African savanna,",
    "I sometimes wonder if",
    "Rivers have shaped the",
    "Looking at it now,",
    "I think most people",
    "Stars in the night sky",
    "To be fair, I",
    "I've spent a while",
    "The truth is, I",
    "I wasn't expecting this,",
    "Just the other day,",
    "I still can't believe",
    "My take on this",
    "Personally, I think",
    "I mean, when you",
    "What surprised me was",
    "I've always felt that",
    "It turns out that",
    "The natural cycle of",
    "I genuinely believe that",
    "So the thing is,",
    "I stumbled across this",
    "You probably already know",
    "I tried to figure",
    "From what I can",
    "The vast expanse of space",
    "I realized the other",
    "Water is perhaps the most",
    "Weather systems often form",
    "What I find interesting",
    # --- Culture / arts / society ---
    "I never thought about",
    "The more I learn,",
    "Art has the power to",
    "Books have shaped the way",
    "Communities around the world",
    "Cultural traditions often reveal",
    "Dance has been a form",
    "Education systems vary widely",
    "Festivals and celebrations mark",
    "Food traditions tell the story",
    "Gardens have served as",
    "Great thinkers of the past",
    "Human ingenuity has always",
    "In the realm of music,",
    "Innovation rarely happens in",
    "Language is one of the most",
    "Libraries have long served as",
    "Literature from this period",
    "Maps were once considered",
    "Merchants and traders of old",
    "Music has an extraordinary",
    "Oral traditions preserved the",
    "Painters of the Renaissance",
    "People have always gathered",
    "Philosophy asks some of the",
    "Poetry has the unique ability",
    "Public spaces have always",
    "Storytelling is one of the",
    "The art of navigation",
    "The craft of glassmaking",
    "I learned a lot about",
    "The evolution of language",
    "The exchange of ideas between",
    "The history of medicine",
    "The invention of the printing",
    "The practice of meditation",
    "The role of education in",
    "The spread of knowledge through",
    "The tradition of craftsmanship",
    "The written word has",
    "Theater and performance have",
    "Trade routes once connected",
    "Travelers in the ancient world",
    "Villages along the coast",
    "Wisdom passed down through",
    "Writers of the eighteenth",
    # --- Narrative / story-like ---
    "A chance encounter at",
    "A curious pattern emerged",
    "A letter arrived one morning",
    "A long-forgotten manuscript",
    "A peculiar thing happened",
    "A small team of researchers",
    "A strange silence fell over",
    "An unexpected discovery in",
    "As dawn broke over the",
    "As the seasons changed,",
    "By the time anyone noticed,",
    "Early one autumn morning,",
    "Elsewhere in the region,",
    "For reasons no one fully",
    "Hidden among the shelves,",
    "In a quiet village near",
    "In the summer of that year,",
    "It all started with a simple",
    "Late one evening, a curious",
    "News of the finding spread",
    "No one expected that a",
    "Nothing could have prepared",
    "On a clear winter night,",
    "On the outskirts of town,",
    "Something remarkable happened",
    "The expedition set out from",
    "The first clue appeared in",
    "The journey was long and",
    "The morning sun revealed",
)

# Pre-sort by length descending for unambiguous longest-prefix matching.
_SORTED_PHRASES = sorted(SEED_PHRASES, key=len, reverse=True)


def select_seed(data: bytes, attempt: int = 0) -> str:
    """Pick a seed phrase deterministically from the SHA-256 hash of *data*.

    Args:
        data: The payload bytes to hash.
        attempt: Retry counter.  Each value produces a different seed phrase,
            allowing the codec to try alternative seeds when a tokenizer
            round-trip mismatch is detected.
    """
    h = hashlib.sha256(data + attempt.to_bytes(2, "big")).digest()
    idx = int.from_bytes(h[:2], "big") % len(SEED_PHRASES)
    return SEED_PHRASES[idx]


def match_seed(cover_text: str) -> tuple[str, str]:
    """Find the seed phrase that prefixes *cover_text*.

    Returns:
        A tuple of ``(seed_phrase, remainder)`` where *remainder* is the cover
        text with the seed phrase stripped.

    Raises:
        ValueError: If no known seed phrase matches the start of *cover_text*.
    """
    for phrase in _SORTED_PHRASES:
        if cover_text.startswith(phrase):
            return phrase, cover_text[len(phrase):]
    raise ValueError(
        "Cover text does not start with any known seed phrase. "
        "It may have been encoded with a different version or a custom prompt."
    )
